# Generated by Django 6.0 on 2026-01-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goCart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
    ]
